### ISSUE TITLE
SyntaxError: Unexpected token 'else' while compiling ejs

### ISSUE THREAD

**Issue by roderik** [rw3iss/nestjs-gen#1]
```
Generating model 	to: /Users/roderik/Development/bpaas-enteth/packages/enteth-explorer/modules/block/block.model.ts
Generating module 	to: /Users/roderik/Development/bpaas-enteth/packages/enteth-explorer/modules/block/block.module.ts
Generating repository 	to: /Users/roderik/Development/bpaas-enteth/packages/enteth-explorer/modules/block/block.repository.ts
Generating controller 	to: /Users/roderik/Development/bpaas-enteth/packages/enteth-explorer/modules/block/block.controller.ts
Generating service 	to: /Users/roderik/Development/bpaas-enteth/packages/enteth-explorer/modules/block/block.service.ts
/Users/roderik/.nvm/versions/node/v14.5.0/lib/node_modules/nestjs-gen/node_modules/ejs/lib/ejs.js:260
    throw err;
    ^

SyntaxError: Unexpected token 'else' while compiling ejs
    at new Function (<anonymous>)
    at Object.exports.compile (/Users/roderik/.nvm/versions/node/v14.5.0/lib/node_modules/nestjs-gen/node_modules/ejs/lib/ejs.js:253:14)
    at /Users/roderik/.nvm/versions/node/v14.5.0/lib/node_modules/nestjs-gen/lib/generator.js:22:22
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

**Comment by rw3iss** [comment]
Will fix tonight or feel free to.

**Comment by roderik** [comment]
Sorry for the brief report, was getting frustrated making a million files and found your cli on Reddit, gave it a quick try while doing something else and wanted to report asap.

**Comment by rw3iss** [comment]
Np am driving can look in 1hr

**Comment by rw3iss** [comment]
@roderik Fix pushed. Sorry about that!
